# Generated by Django 5.2.4 on 2025-08-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlacklistedToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField(verbose_name="令牌")),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="原因"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "黑名单令牌",
                "verbose_name_plural": "黑名单令牌",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login_type",
                    models.CharField(
                        choices=[
                            ("wechat", "微信登录"),
                            ("password", "密码登录"),
                            ("sms", "短信验证码登录"),
                            ("token", "令牌登录"),
                        ],
                        max_length=20,
                        verbose_name="登录类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "成功"), ("failed", "失败")],
                        max_length=20,
                        verbose_name="登录状态",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="设备ID"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "登录日志",
                "verbose_name_plural": "登录日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SmsVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=11, verbose_name="手机号")),
                ("code", models.CharField(max_length=6, verbose_name="验证码")),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("login", "登录"),
                            ("register", "注册"),
                            ("reset_password", "重置密码"),
                            ("bind_phone", "绑定手机"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="用途",
                    ),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="是否已使用")),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="使用时间"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "短信验证码",
                "verbose_name_plural": "短信验证码",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WechatAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openid",
                    models.CharField(max_length=64, unique=True, verbose_name="OpenID"),
                ),
                (
                    "unionid",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="UnionID"
                    ),
                ),
                ("session_key", models.CharField(max_length=128, verbose_name="会话密钥")),
                (
                    "nickname",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="微信昵称"
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True, max_length=255, null=True, verbose_name="头像URL"
                    ),
                ),
                (
                    "gender",
                    models.IntegerField(blank=True, null=True, verbose_name="性别"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="国家"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="省份"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="城市"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="语言"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后登录时间"),
                ),
            ],
            options={
                "verbose_name": "微信认证信息",
                "verbose_name_plural": "微信认证信息",
            },
        ),
    ]
