# Generated by Django 5.2.4 on 2025-08-03 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth_app", "0001_initial"),
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blacklistedtoken",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blacklisted_tokens",
                to="user_app.user",
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="loginlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_logs",
                to="user_app.user",
                verbose_name="用户",
            ),
        ),
        migrations.AddIndex(
            model_name="smsverification",
            index=models.Index(
                fields=["phone", "created_at"], name="auth_app_sm_phone_4b8d4a_idx"
            ),
        ),
        migrations.AddField(
            model_name="wechatauth",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wechat_auth",
                to="user_app.user",
                verbose_name="用户",
            ),
        ),
        migrations.AddIndex(
            model_name="blacklistedtoken",
            index=models.Index(fields=["token"], name="auth_app_bl_token_560f68_idx"),
        ),
        migrations.AddIndex(
            model_name="blacklistedtoken",
            index=models.Index(
                fields=["expires_at"], name="auth_app_bl_expires_a37cbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginlog",
            index=models.Index(
                fields=["user", "created_at"], name="auth_app_lo_user_id_22b5eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginlog",
            index=models.Index(
                fields=["ip_address", "created_at"],
                name="auth_app_lo_ip_addr_998a3d_idx",
            ),
        ),
    ]
