# Generated by Django 5.2.4 on 2025-08-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="重量(吨)"
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="体积(立方米)",
                    ),
                ),
                (
                    "goods_type",
                    models.CharField(default="沥青", max_length=50, verbose_name="货物类型"),
                ),
                (
                    "from_location",
                    models.CharField(max_length=255, verbose_name="装货地点"),
                ),
                (
                    "from_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="装货地点经度",
                    ),
                ),
                (
                    "from_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="装货地点纬度",
                    ),
                ),
                ("to_location", models.CharField(max_length=255, verbose_name="卸货地点")),
                (
                    "to_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="卸货地点经度",
                    ),
                ),
                (
                    "to_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="卸货地点纬度",
                    ),
                ),
                ("loading_time", models.DateTimeField(verbose_name="装货时间")),
                (
                    "expected_arrival_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="期望到达时间"),
                ),
                (
                    "expected_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="期望价格",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待接单"),
                            ("accepted", "已接单"),
                            ("in_transit", "运输中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "货源信息",
                "verbose_name_plural": "货源信息",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoodsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=255, verbose_name="图片URL")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="图片描述"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "货源图片",
                "verbose_name_plural": "货源图片",
                "ordering": ["created_at"],
            },
        ),
    ]
