# Generated by Django 5.2.4 on 2025-08-03 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("goods_app", "0001_initial"),
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods",
                to="user_app.user",
                verbose_name="货主",
            ),
        ),
        migrations.AddField(
            model_name="goodsimage",
            name="goods",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="goods_app.goods",
                verbose_name="货源",
            ),
        ),
    ]
