# Generated by Django 5.2.4 on 2025-08-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(max_length=20, unique=True, verbose_name="订单编号"),
                ),
                (
                    "freight_fee",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="运费"
                    ),
                ),
                (
                    "deposit",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="定金"
                    ),
                ),
                (
                    "other_fees",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="其他费用"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="总金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "待支付"),
                            ("pending_loading", "待装货"),
                            ("in_transit", "运输中"),
                            ("delivered", "已送达"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                            ("disputed", "有争议"),
                        ],
                        default="pending_payment",
                        max_length=20,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "未支付"),
                            ("partial_paid", "部分支付"),
                            ("paid", "已支付"),
                            ("refunded", "已退款"),
                        ],
                        default="unpaid",
                        max_length=20,
                        verbose_name="支付状态",
                    ),
                ),
                ("expected_loading_time", models.DateTimeField(verbose_name="预计装货时间")),
                (
                    "actual_loading_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="实际装货时间"),
                ),
                ("expected_delivery_time", models.DateTimeField(verbose_name="预计送达时间")),
                (
                    "actual_delivery_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="实际送达时间"),
                ),
                (
                    "shipper_notes",
                    models.TextField(blank=True, null=True, verbose_name="货主备注"),
                ),
                (
                    "driver_notes",
                    models.TextField(blank=True, null=True, verbose_name="车主备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("loading_receipt", "装货单"),
                            ("delivery_receipt", "送货单"),
                            ("invoice", "发票"),
                            ("contract", "合同"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="文档类型",
                    ),
                ),
                ("document_url", models.URLField(max_length=255, verbose_name="文档URL")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="文档描述"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "订单文档",
                "verbose_name_plural": "订单文档",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "待支付"),
                            ("pending_loading", "待装货"),
                            ("in_transit", "运输中"),
                            ("delivered", "已送达"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                            ("disputed", "有争议"),
                        ],
                        max_length=20,
                        verbose_name="原状态",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "待支付"),
                            ("pending_loading", "待装货"),
                            ("in_transit", "运输中"),
                            ("delivered", "已送达"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                            ("disputed", "有争议"),
                        ],
                        max_length=20,
                        verbose_name="新状态",
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "订单状态日志",
                "verbose_name_plural": "订单状态日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1, max_digits=2, verbose_name="评分"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="评价内容"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "评价",
                "verbose_name_plural": "评价",
                "ordering": ["-created_at"],
            },
        ),
    ]
