# Generated by Django 5.2.4 on 2025-08-03 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("goods_app", "0002_initial"),
        ("order_app", "0001_initial"),
        ("user_app", "0001_initial"),
        ("vehicle_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="driver_orders",
                to="user_app.user",
                verbose_name="车主",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="goods",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="goods_app.goods",
                verbose_name="货源",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipper_orders",
                to="user_app.user",
                verbose_name="货主",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="vehicle_app.vehicle",
                verbose_name="车辆",
            ),
        ),
        migrations.AddField(
            model_name="orderdocument",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="order_app.order",
                verbose_name="订单",
            ),
        ),
        migrations.AddField(
            model_name="orderstatuslog",
            name="operator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operated_logs",
                to="user_app.user",
                verbose_name="操作人",
            ),
        ),
        migrations.AddField(
            model_name="orderstatuslog",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_logs",
                to="order_app.order",
                verbose_name="订单",
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_ratings",
                to="user_app.user",
                verbose_name="评价人",
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="order_app.order",
                verbose_name="订单",
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_ratings",
                to="user_app.user",
                verbose_name="被评价人",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("order", "from_user", "to_user")},
        ),
    ]
