# Generated by Django 5.2.4 on 2025-08-03 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("order_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("create", "创建支付"),
                            ("update", "更新支付"),
                            ("notify", "支付通知"),
                            ("refund", "退款"),
                            ("error", "错误"),
                        ],
                        max_length=20,
                        verbose_name="日志类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="日志内容")),
                ("data", models.JSONField(blank=True, null=True, verbose_name="日志数据")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "支付日志",
                "verbose_name_plural": "支付日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="余额"
                    ),
                ),
                (
                    "frozen_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="冻结金额"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "钱包",
                "verbose_name_plural": "钱包",
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_number",
                    models.CharField(max_length=32, unique=True, verbose_name="交易编号"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="金额"
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="交易前余额"
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="交易后余额"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "充值"),
                            ("withdraw", "提现"),
                            ("payment", "支付"),
                            ("refund", "退款"),
                            ("adjustment", "调整"),
                        ],
                        max_length=20,
                        verbose_name="交易类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "处理中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="交易状态",
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "钱包交易记录",
                "verbose_name_plural": "钱包交易记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_number",
                    models.CharField(max_length=32, unique=True, verbose_name="支付编号"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="金额"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("deposit", "定金"),
                            ("balance", "尾款"),
                            ("full", "全款"),
                            ("refund", "退款"),
                        ],
                        max_length=20,
                        verbose_name="支付类型",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("wechat", "微信支付"),
                            ("alipay", "支付宝"),
                            ("bank_transfer", "银行转账"),
                            ("cash", "现金"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="支付方式",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("success", "支付成功"),
                            ("failed", "支付失败"),
                            ("cancelled", "已取消"),
                            ("refunded", "已退款"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="支付状态",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="交易ID"
                    ),
                ),
                (
                    "transaction_data",
                    models.JSONField(blank=True, null=True, verbose_name="交易数据"),
                ),
                ("remark", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="支付时间"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="order_app.order",
                        verbose_name="订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "支付",
                "verbose_name_plural": "支付",
                "ordering": ["-created_at"],
            },
        ),
    ]
