# Generated by Django 5.2.4 on 2025-08-03 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("order_app", "0002_initial"),
        ("payment_app", "0001_initial"),
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments_received",
                to="user_app.user",
                verbose_name="收款人",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments_made",
                to="user_app.user",
                verbose_name="付款人",
            ),
        ),
        migrations.AddField(
            model_name="paymentlog",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="payment_app.payment",
                verbose_name="支付",
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet",
                to="user_app.user",
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="related_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wallet_transactions",
                to="order_app.order",
                verbose_name="关联订单",
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="related_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wallet_transactions",
                to="payment_app.payment",
                verbose_name="关联支付",
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="payment_app.wallet",
                verbose_name="钱包",
            ),
        ),
    ]
